# Generated by Django 2.2 on 2020-09-21 19:34

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='TextBlockUrl',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('url', models.CharField(max_length=1024, verbose_name='url страницы')),
				('order_number', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
				('name', models.CharField(max_length=1024, verbose_name='Название')),
				('date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата')),
				('text', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст')),
				(
				'image', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка')),
				('isHidden', models.BooleanField(blank=True, verbose_name='Скрыть')),
			],
			options={
				'verbose_name_plural': 'Текстовый блок (ссылка)',
				'ordering': ['order_number'],
			},
		),
	]
