# Generated by Django 2.2 on 2020-09-21 19:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True
	
	dependencies = [
	]
	
	operations = [
		migrations.CreateModel(
			name='News',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('order_number', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
				('name', models.CharField(max_length=1024, verbose_name='Название')),
				('slug', models.SlugField(blank=True, max_length=1024, null=True, verbose_name='Название латинское')),
				('date', models.DateTimeField(verbose_name='Дата')),
				('description', tinymce.models.HTMLField(verbose_name='Описание')),
				('text', tinymce.models.HTMLField(verbose_name='Текст')),
				(
					'image',
					models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка')),
				('title_main',
				 models.CharField(blank=True, max_length=1024, null=True, verbose_name='Заголовок страницы')),
				('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова (мета)')),
				('keywords_description', models.TextField(blank=True, null=True, verbose_name='Описание (мета)')),
				('is_hidden', models.BooleanField(blank=True, verbose_name='Скрыть')),
			],
			options={
				'verbose_name_plural': 'Новости',
				'ordering': ['-date'],
			},
		),
	]
