version: "3.8"
services:
  app:
    user: me
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    volumes:
    - ../:/app
#  mariadb:
#    user: me
#    build:
#      context: ../
#      dockerfile: docker/mariadb/Dockerfile
#    ports:
#    - 13306:3306
#    environment:
#      MYSQL_RANDOM_ROOT_PASSWORD: 1
#      MYSQL_USER: woland
#      MYSQL_PASSWORD: woland
#      MYSQL_DATABASE: woland
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ../static:/app/static
      - type: bind
        target: /tmp/logs
        source: ./data/nginx/logs
    ports:
      - ${WEB_PORT}:8000
