# Generated by Django 2.2 on 2020-09-21 23:07

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('project_settings', '0002_auto_20200922_0022'),
	]

	operations = [
		migrations.AddField(
			model_name='projectsettings',
			name='title_text_index',
			field=models.CharField(blank=True, max_length=256, null=True,
								   verbose_name='Заголовок текста на главной странице'),
		),
		migrations.AlterField(
			model_name='projectsettings',
			name='text_category',
			field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст (статический) в категории'),
		),
		migrations.AlterField(
			model_name='projectsettings',
			name='text_index',
			field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст на главной странице'),
		),
	]
