# Generated by Django 2.2 on 2020-11-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0003_auto_20200922_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='count_staff',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Количество сотрудников'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='start_year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Год основания'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='type_company',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип компании'),
        ),
    ]
