# Generated by Django 2.2 on 2020-10-30 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('menu', '0014_product_is_manufacture'),
		('checkout', '0001_initial'),
	]
	
	operations = [
		migrations.AddField(
			model_name='order',
			name='type_order',
			field=models.CharField(default='', max_length=128, verbose_name='Тип'),
		),
		migrations.AlterField(
			model_name='order',
			name='email',
			field=models.EmailField(blank=True, default='', max_length=50, null=True, verbose_name='E-mail'),
		),
		migrations.AlterField(
			model_name='order',
			name='file',
			field=models.FileField(blank=True, editable=False, null=True, upload_to='uploads/files',
								   verbose_name='Файл'),
		),
		migrations.CreateModel(
			name='CartItem',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('cart_id', models.CharField(max_length=50)),
				('date_added', models.DateTimeField(auto_now_add=True)),
				('quantity', models.IntegerField(default=1)),
				('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
											  to='menu.Product')),
			],
			options={
				'db_table': 'cart_items',
				'ordering': ['date_added'],
			},
		),
	]
