# Generated by Django 2.2 on 2020-09-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filials', '0002_auto_20200922_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filials',
            name='robots',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое robots.txt'),
        ),
    ]
