# Generated by Django 2.2 on 2020-09-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=512, verbose_name='Исходное слово')),
                ('result', models.CharField(max_length=512, verbose_name='Синоним')),
            ],
            options={
                'verbose_name_plural': 'Талица синонимов (замен) поиска',
            },
        ),
        migrations.CreateModel(
            name='SearchRemove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_remove', models.CharField(max_length=512, verbose_name='Исключаемое слово')),
            ],
            options={
                'verbose_name_plural': 'Талица исключений поиска',
            },
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=512, verbose_name='Запрос пользователя')),
                ('q_change', models.CharField(default='', max_length=512, verbose_name='Искомая фраза')),
                ('search_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP пользователя')),
                ('path_site', models.CharField(default='', max_length=1024, verbose_name='Страница с которой искали')),
                ('filial_name', models.CharField(default='', max_length=1024, verbose_name='Название города (по поддомену)')),
                ('subdomain_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название поддомена')),
                ('tracking_id', models.CharField(default='', editable=False, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Поисковые запросы',
                'ordering': ['-search_date'],
            },
        ),
    ]
