# Generated by Django 2.2 on 2020-09-21 21:21

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standart', '0001_initial'),
        ('marka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название пункта')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Название латинское')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('label_param1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название параметра 1')),
                ('ed_izm_param1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ед. изм. параметра 1')),
                ('label_param2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название параметра 2')),
                ('ed_izm_param2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ед. изм. параметра 2')),
                ('label_param3', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название параметра 3')),
                ('ed_izm_param3', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ед. изм. параметра 3')),
                ('label_param4', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название параметра 4')),
                ('ed_izm_param4', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ед. изм. параметра 4')),
                ('label_param5', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название параметра 5')),
                ('ed_izm_param5', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ед. изм. параметра 5')),
                ('label_param6', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название параметра 6')),
                ('ed_izm_param6', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ед. изм. параметра 6')),
                ('label_param7', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название параметра 7')),
                ('ed_izm_param7', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ед. изм. параметра ')),
                ('is_hide_marka', models.BooleanField(blank=True, verbose_name='Скрыть марку')),
                ('is_hide_standart', models.BooleanField(blank=True, verbose_name='Скрыть ГОСТ')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('flag_footer', models.BooleanField(verbose_name='Отображать в подвале')),
                ('title_main', models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок страницы')),
                ('keywords', models.TextField(blank=True, help_text='Ключевые слова для SEO продвижения (через запятую). Мета тэг - keywords', null=True, verbose_name='Ключевые слова (мета)')),
                ('keywords_description', models.TextField(blank=True, help_text='Содержимое мета тэга - description', null=True, verbose_name='Описание (мета)')),
                ('is_hidden', models.BooleanField(verbose_name='Скрыть')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.MenuCatalog', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name_plural': 'Меню/Каталог',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='TypeMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название типа')),
                ('template', models.CharField(max_length=1024, verbose_name='Название файла шаблона')),
            ],
            options={
                'verbose_name_plural': 'Тип меню',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Приоритет (Порядковый номер)')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=1024, null=True, verbose_name='Название латинское')),
                ('param_1', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 1')),
                ('param_1_slug', models.SlugField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 1 slug')),
                ('param_2', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 2')),
                ('param_2_slug', models.SlugField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 2 slug')),
                ('param_3', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 3')),
                ('param_3_slug', models.SlugField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 3 slug')),
                ('param_4', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 4')),
                ('param_4_slug', models.SlugField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 4 slug')),
                ('param_5', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 5')),
                ('param_5_slug', models.SlugField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 5 slug')),
                ('param_6', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 6')),
                ('param_6_slug', models.SlugField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 6 slug')),
                ('param_7', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 7')),
                ('param_7_slug', models.SlugField(blank=True, default='', max_length=128, null=True, verbose_name='Параметр 7 slug')),
                ('available', models.CharField(blank=True, max_length=128, null=True, verbose_name='Наличие')),
                ('ed_izm', models.CharField(blank=True, max_length=128, null=True, verbose_name='Единицы измерения')),
                ('price', models.CharField(blank=True, max_length=128, null=True, verbose_name='Цена')),
                ('image', models.CharField(blank=True, max_length=256, null=True, verbose_name='Картинка основная')),
                ('image_2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Картинка 2')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('vendor', models.CharField(blank=True, max_length=128, null=True, verbose_name='Производитель')),
                ('vendor_country', models.CharField(blank=True, max_length=128, null=True, verbose_name='Страна производителя')),
                ('method_of_manufacture', models.CharField(blank=True, max_length=128, null=True, verbose_name='Способ изготовления')),
                ('title_main', models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок страницы')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова (мета)')),
                ('keywords_description', models.TextField(blank=True, null=True, verbose_name='Описание (мета)')),
                ('isHidden', models.BooleanField(verbose_name='Скрыть')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MenuCatalog', verbose_name='Категория металлопроката')),
                ('marka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marka.Marka', verbose_name='Марка')),
                ('standart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standart.Standart', verbose_name='ГОСТ')),
            ],
            options={
                'verbose_name_plural': 'Продукт',
                'ordering': ['catalog'],
            },
        ),
        migrations.AddField(
            model_name='menucatalog',
            name='type_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.TypeMenu', verbose_name='Тип меню'),
        ),
        migrations.AddField(
            model_name='menucatalog',
            name='uslugi',
            field=models.ManyToManyField(blank=True, db_table='MenuCatalog_and_uslugi_MenuCatalog', related_name='_menucatalog_uslugi_+', to='menu.MenuCatalog', verbose_name='Услуги'),
        ),
    ]
