# Generated by Django 2.2 on 2020-09-22 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200922_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucatalog',
            name='text_service',
        ),
    ]
