# Generated by Django 2.2 on 2020-09-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_menucatalog_text_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucatalog',
            name='text_service',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст для карточки услуги'),
        ),
    ]
