# Generated by Django 2.2 on 2020-09-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('menu', '0007_auto_20200924_0011'),
	]
	
	operations = [
		migrations.AddField(
			model_name='product',
			name='is_spec',
			field=models.BooleanField(default=False, verbose_name='Спецпредложение'),
		),
		migrations.AddField(
			model_name='product',
			name='is_usluga',
			field=models.BooleanField(default=False, verbose_name='Услуга'),
		),
	]
